spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testLibrary
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:  update # ??? validate, ??? create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: qeadzc4065@gmail.com
    password: qomu ndly fwvj peoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

