spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testLibrary
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:  update # ??? validate, ??? create-drop
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
